### ISSUE TITLE
check that rewards are generated and paid on shelley_qa (using ledger-state)

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#1008]
One important test we can do is to check that rewards are paid on different small testnets (shelley_qa, alonzo, etc) - as an exception, only for these environments, we can have a test checking that rewards are paid by pools (and received by stake addresses) based on `query ledger-state` (this approach would not be useful on Mainnet because of the time and RAM requirements - but it can be investigated).

**Comment by mkoura** [comment]
We already test this by really delegating to a pool and receiving reward.
