### ISSUE TITLE
Single VRF implementation 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#1034]
**AC1** 
- [x] sync speed from a clean state should be “significantly“ faster for the blocks minted after the Vasil HF
> [John] with the changes we should see a faster VRF validation, by ~25%.

**Comment by vfrsilva** [comment]
To clarify on **AC1** - only blocks minted after the Vasil HF will use a single VRF - meaning the entire chain up to the Vasil HF epoch will still validate using the two VRFs.

**Comment by vfrsilva** [comment]
@dorin100 can you please adjust AC according to my earlier comment?
Thanks!
