### ISSUE TITLE
run sync tests on all devops snapshots

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#1087]
- run db-sync sync tests on the snapshots provided by devops for Mainnet & Testnet

**Comment by ArturWieczorek** [comment]
IOHK Snapshot restoration  GitHub Actions flow supports any url user will provide for snapshot field. 

Additionally there is a `latest` keyword that can be used in `snapshot url` field - it will pick the latest available IOHK snapshot for particular environment that supports snapshots.
