### ISSUE TITLE
new opCert functionality

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#1117]
**Desired functionality:**
- The op cert counter must be exactly one more than the previously used op cert; It's the last counter actually used on the chain that is important.
- Previously op cert issue numbers could be anything, provided it was larger than previously used numbers. Now it can only be exactly one more.
 

**Open questions**:
- When you issue an invalid opcert by mistake, how do you "revert" the counter so you can issue a valid one?
R: If you have the cold key and know what the counter value is supposed to be there's a CLI command in node --> `cardano-cli node new-counter`

- Should SPOs backup their counter file before issuing a new opcert?
R: not necessarily 

- How do you know what is the actual opcert value used on-chain?
R: from using the "query kes-info" command

**Comment by mkoura** [comment]
@gitmachtl SPO should be able to query opcert info once https://github.com/input-output-hk/cardano-node/pull/3945 is merged.
