### ISSUE TITLE
Test for ledger behaviour when handling Byron addresses for Plutus V1 in Alonzo and Babbage

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node-tests#1150]
There's a difference in how ledger constructs script context for Plutus V1 scripts in Alonzo and Babbage. If a transaction contains Byron addresses in Alonzo era then they are included in the script context, but in Babbage era it is a phase1 validation failure. We should have a couple of tests for these scenarios.

**Comment by saratomaz** [comment]
check `test_spend_reference_script` and `test_lock_byron_reference_script`
