### ISSUE TITLE
Automate multisig functionality

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#121]
https://github.com/input-output-hk/cardano-node/pull/1788

https://github.com/input-output-hk/cardano-node/blob/a3bd79e41363133e098367526ba9c68333ead18c/doc/reference/multisig.md

**Comment by dorin100** [comment]
Manual tests executed on PR1788

Waiting for PR to be merged in order to execute the final testing + automation.

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/144
https://github.com/input-output-hk/cardano-node-tests/pull/139

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/149
