### ISSUE TITLE
Document all the tested scenarios

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#1232]
create a list (similarly to the auto-generated HTML report - or even better in the Allure format) with all the existing/executed tests 
- it should be clear what/when is run (nightly, long-duration, sanity, upgrade scenario, db-sync, etc)

**Comment by mkoura** [comment]
We have this for every testrun, or am I missing something?

**Comment by dorin100** [comment]
nope - we have this in the allure report
