### ISSUE TITLE
Plutus v2 tests with dedicated plutus scripts

### ISSUE THREAD

**Issue by saratomaz** [input-output-hk/cardano-node-tests#1261]
**Reference inputs** #993 
- [x] Reference an input and run a Plutus script validating that it has visibility of it (to prove that a utxo created pre-Vasil can be referenced and is useful to Plutus)

**Inline datums** #994 
- [x] Reference two outputs that both hold the exact same datum (TxInfo should behave correctly) 
- [x] Run a Plutus script validating that it has visibility of inline datums (and datum hash still)

**Reference scripts** #995 
- [x] run a Plutus script validating that the correct script hash is attached to the input

**Comment by dorin100** [comment]
@james-iohk can you please sync with @saratomaz on what would be required here in case you will have the time and possibility to help?

**Comment by saratomaz** [comment]
> @james-iohk can you please sync with @saratomaz on what would be required here in case you will have the time and possibility to help?

I already talked with James, he will update the ticket when he has the scripts ready

**Comment by james-iohk** [comment]
@dorin100 Yeah, I'll produce some scripts along with test vectors and provide here.

**Comment by james-iohk** [comment]
[test_1261.zip](https://github.com/input-output-hk/cardano-node-tests/files/9287319/test_1261.zip)
@saratomaz here are scripts for each of the three above. Let me know if you have any questions.
