### ISSUE TITLE
Add plutus tests for SECP256k1 Schnorr and ECDSA builtins 

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/cardano-node-tests#1269]
It would be good to prove that these functions are usable (or not usable in the case of high budget requirement in V2 cost model).
We can refer to here for policy and test vectors: https://input-output.atlassian.net/wiki/spaces/QA/pages/3518202008/SECP256k1+Testing

**Comment by james-iohk** [comment]
[SECP265k_scriptdata.zip](https://github.com/input-output-hk/cardano-node-tests/files/9606498/SECP265k_scriptdata.zip)

**Comment by saratomaz** [comment]
Tests can be found in the class `TestSECP256k1` at the files:
- test_plutus_v2_mint_build.py
- test_plutus_v2_mint_raw.py
- test_plutus_v2_spend_build.py
- test_plutus_v2_spend_raw.py
