### ISSUE TITLE
Add test for datum round-trip corrupts datum bytes

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-node-tests#1303]
Details:
https://github.com/input-output-hk/cardano-db-sync/issues/1214

**Comment by mkoura** [comment]
Done - https://github.com/input-output-hk/cardano-node-tests/blob/f250e2ef70c9ff8ee6193c341339b2b2bcab930d/cardano_node_tests/tests/test_plutus_v2_spend_raw.py#L353-L424
