### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/cardano-node-tests#1471]
This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:

Explain how to make a contribution (Contributing MD)
Include the Standard Code of Conduct
Use the Apache 2.0 License or agreed alternative
Identify the Core Maintainers

**Comment by mkoura** [comment]
Done.
