### ISSUE TITLE
Re-register a stake pool that is in course of being retired

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#152]
related to https://github.com/input-output-hk/cardano-node/issues/1877

1. create and register a stake pool
2. retire the pool (create and submit a pool de-registration certificate)
3. before the pool is retired (at the specified epoch), submit a new registration certificate (same keys, vrf, etc) - this should overrule the deregistration certificate

Check that:
1. the pool is not deregistered anymore
2.  the pool registration deposit is not returned to the pool owner after the pool should have been deregistered

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/177
