### ISSUE TITLE
Rewards to multiple addresses

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#168]
1. Create a new stake pool with separate addresses for operator, owner, rewards
2. Delegate all addresses/wallets to the pool
3. Start the pool
4. Wait for the stake to become effective and for the pool to start to create blocks
5. Wait for all 3 addresses to receive some rewards
6. Wait for the rewards received by the 3 addresses to become active in delegation
7. Wait for the pool to create blocks 
8. Wait for the addresses to receive rewards 
9. Check the rewards received by all 3 addresses - operator, owner, rewards

More details here: https://github.com/input-output-hk/cardano-node/issues/1964

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/186
