### ISSUE TITLE
CIP 1694 governance action

### ISSUE THREAD

**Issue by saratomaz** [input-output-hk/cardano-node-tests#1835]
CIP 1694 introduces different types of governance actions. A governance action is an on-chain event that is triggered by a transaction and has a deadline after which it cannot be enacted.

1. An action is said to be **ratified** when it gathers enough votes in its favor (through the rules and parameters that are detailed below).
2. An action that doesn't collect sufficient Yes votes before its deadline is said to have **expired**.
3. An action that has been ratified is said to be **enacted** once it has been activated on the network.

With `cardano-cli governance action` is possible:
- [ ] `create-no-confidence-motion `
_A motion to create a state of no-confidence in the current constitutional committee_
- [ ] `create-new-committee`
_Changes to the members of the constitutional committee and/or to its signature threshold_
- [ ] `create-constitution-update`
_A modification to the off-chain Constitution, recorded as an on-chain hash of the text document_
- [ ] `create-hard-fork-initiation`
_Triggers a non-backwards compatible upgrade of the network; requires a prior software upgrade_
- [ ] `create-protocol-parameter-update`
_Any change to one or more updatable protocol parameters, excluding changes to major protocol versions ("hard forks")_
- [ ] `create-treasury-withdrawal`
_Movements from the treasury, sub-categorized into small, medium or large withdrawals (based on the amount of Lovelace to be withdrawn)._
- [ ] `create-info`
_An action that has no effect on-chain, other than an on-chain record._
- [ ] `view`
- [ ] `query`
- [ ] `submit`

Detailed info: https://www.1694.io/

**Comment by mkoura** [comment]
Replaced by https://input-output-hk.github.io/cardano-node-tests/test-plans/100_conway_governance.html
