### ISSUE TITLE
CIP 1694 governance vote

### ISSUE THREAD

**Issue by saratomaz** [input-output-hk/cardano-node-tests#1838]
With` cardano-cli governance vote` is possible:

- [ ] `create`
- [ ] `view`
- [ ] `submit`

1. For SPOs and DReps, the number of votes it's proportional to the Lovelace that is delegated to them at the point the action is checked for ratification. 
2. For constitututional committee members, each current committee member has one vote. 
3. Votes from unregistered SPOs or DReps count as having zero stake.

Votes can be cast multiple times for each governance action by a single credential. Correctly submitted votes override any older votes for the same credential and role. That is, the voter may change their position on any action if they choose. As soon as a governance action is ratified, voting ends and transactions containing further votes are invalid.

Detailed info: https://www.1694.io/

**Comment by mkoura** [comment]
Replaced by https://input-output-hk.github.io/cardano-node-tests/test-plans/100_conway_governance.html
