### ISSUE TITLE
CIP 1694 drep

### ISSUE THREAD

**Issue by saratomaz** [input-output-hk/cardano-node-tests#1839]
A DRep is a group of delegate representatives. Any Ada holder may register to be a DRep and so choose to represent themselves and/or others.

With `cardano-cli drep` is possible:

- [ ] `registration-certificate`
- [ ] `deregistration-certificate`
- [ ] `id`
- [ ] `metadata-hash`

Detailed info: https://www.1694.io/

**Comment by mkoura** [comment]
Replaced by https://input-output-hk.github.io/cardano-node-tests/test-plans/100_conway_governance.html
