### ISSUE TITLE
CIP 1694 stake-pool

### ISSUE THREAD

**Issue by saratomaz** [input-output-hk/cardano-node-tests#1840]
Concerning to `cardano-cli stake-pool`

As with stake pools, Ada holders may delegate their voting rights to any other DRep.
- [ ] `drep-delegation-certificate`

The `delegation-certificate` command will be renamed to `pool-delegation-certificate`

**Comment by mkoura** [comment]
Replaced by https://input-output-hk.github.io/cardano-node-tests/test-plans/100_conway_governance.html
