### ISSUE TITLE
[QA] - Sign stakepool certificate transaction in multiple stages

### ISSUE THREAD

**Issue by alan-mcnicholas** [input-output-hk/cardano-node-tests#2]
The purpose of this item is to track the testing and verification of the functionality provided by https://github.com/input-output-hk/cardano-node/issues/1054. This is also a good candidate for automation! :)

**Comment by dorin100** [comment]
https://github.com/input-output-hk/cardano-node/issues/1054

**Comment by dorin100** [comment]
example commands here: https://jira.iohk.io/browse/CAD-1095

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/111
