### ISSUE TITLE
[QA] - Stake distribution

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#20]
Check the stake distribution of the nodes.

Each epoch, the nodes are generating a dump with the state of the epoch --> `cardano-cli shelley query ledger-state --mainnet`

Use the data from the `ledger-state` in order to validate that the correct amount of rewards is generated/calculated for each pool/delegator.

- **_pstakeGo** contains the state (stake) used to calculate rewards (taken at the start of the 'current_epoch - 2')
- _delegations has a key hash and another hash - The first is the delegator key, the second is the pool id

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/186
