### ISSUE TITLE
Stake pool with reward address not registered

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#200]
https://input-output-rnd.slack.com/archives/CC0CLNEH1/p1604382347331100

according to point 3 of section 3.3.4 (design document)
`Should the reward address be unregistered, the stake pool operator will be unable to receive rewards. In that case, any rewards that they would be due are instead sent back to the reserves (but the stake pool members would still get their usual rewards).`

- check rewards received by stake pool and delegators

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/blob/a9457e5e12cf3be5ad608591dd98d3fbedc3d829/cardano_node_tests/tests/test_staking.py#L1516
