### ISSUE TITLE
Tests - check rewards are proportional with the no of blocks created

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#202]
https://github.com/input-output-hk/ouroboros-network/pull/2694

Check the no of blocks created by each pool in each epoch and that the rewards per epoch per pool are proportional with the no of blocks created.

nesBprev = New Epoch State, blocks previous
nesBcur = New Epoch State, blocks current

**Comment by saratomaz** [comment]
present on **test_oversaturated**
