### ISSUE TITLE
[QA] - Signing keys for transactions (negative)

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#23]
- check that it is not possible to successfully submit transactions without the necessary signing keys (payment, certificates, etc)
- add more signing keys as required
- add the same signing key multiple times

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/97
https://github.com/input-output-hk/cardano-node-tests/pull/94
