### ISSUE TITLE
Pool saturation >100% - check the rewards received by the pool/delegators

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#257]
Make sure that the saturation level for the pool is > 100%.
Check the rewards received by the pool/delegators - they should be limited

Details:
- https://docs.cardano.org/en/latest/explore-cardano/glossary.html?highlight=saturation#term-saturation
- https://docs.cardano.org/en/latest/explore-cardano/understanding-pledging-and-rewards.html?highlight=saturation
- https://forum.cardano.org/t/rewards-saturation-also-threatens-non-saturated-pools/39184

**Comment by mkoura** [comment]
Implemented.
