### ISSUE TITLE
transaction with multiple inputs and outputs < 1 Ada

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#259]
It would be nice to see what happens when we have some accounts with 100/1k/10k/100k utxos smaller than 1ADA (up to 1 Lovelace) and then sending transactions between them. 

I see some issues related to this.

We can check:
- that the txs are successful
- that the final balances are correct
- the time to create and mine the txs

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/337
