### ISSUE TITLE
Tests for time locking scripts

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node-tests#267]
See https://github.com/input-output-hk/cardano-node/issues/2157

Currently we have tests only for multisig, no time locking or other scripts features.

**Comment by mkoura** [comment]
Doc in Multi-asset formal specification, section 5 and appendix A
https://github.com/input-output-hk/cardano-ledger-specs

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node/pull/2165/files

**Comment by mkoura** [comment]
https://input-output-rnd.slack.com/archives/G01FSME77U4/p1607086998165800 (internal link)

**Comment by dorin100** [comment]
adding the scenarios here for better tracking:
```
1 & 2: tests that we get OutsideValidityIntervalUTxO when the current slot is before the --lower-bound or after the --upper-bound.
3 & 4: test that we get ScriptWitnessNotValidatingUTXOW when the current slot is before the --lower-bound or after the --upper-bound respectively, but those lower or upper bounds are not after/before the slot no specified in the script.
5 & 6: test that we can spend successfully when the current slot is before the --lower-bound or after the --upper-bound respectively, and those lower or upper bounds are after/before the slot no specified in the script.
```

**Comment by dorin100** [comment]
+ some CLI examples - https://github.com/input-output-hk/cardano-node/blob/jordan/allegra-mary-transition/test_allegra_script/newtx.sh

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/275
