### ISSUE TITLE
multi asset

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#273]
https://docs.google.com/document/d/1Liyj5d177o763xyh8JUhfyOAtRWSfLxNvbjSGGV5tgc/edit#

https://docs.google.com/document/d/1qB1fH-m0wm74NpG5AKZMG4_I9H5n5454CdueWPErnpc/edit#heading=h.cle4pq75kodl

https://github.com/input-output-hk/cardano-node/pull/2177/files

**Comment by dorin100** [comment]
Cover:
	• minting
	• issuing
	• using
	• redeeming
	• burning

**Comment by dorin100** [comment]
test for min_tx_fee for transactions creating new assets

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/302/

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/326

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/317

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/323
