### ISSUE TITLE
[QA] - Create automation framework for running e2e tests into CI

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#30]
Steps for the framework creation:
1. build the cardano-node
2. create and start a local cluster - asked for help from devops
3. execute the python scripts/tests

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests

**Comment by mkoura** [comment]
Integration to CI is covered by issue https://github.com/input-output-hk/cardano-node-tests/issues/51
