### ISSUE TITLE
[QA] - Check Key Evolving Signature Scheme

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#34]
- check what happens when kes period expires
- renew kes keys

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/189

**Comment by dorin100** [comment]
description: 
- https://docs.cardano.org/projects/cardano-node/en/latest/stake-pool-operations/KES_period.html?highlight=kes
- https://docs.cardano.org/projects/cardano-node/en/latest/reference/shelley-genesis.html?highlight=kes

- create a KES key pair:
```
cardano-cli shelley node key-gen-KES \
    --verification-key-file pool_kes.vkey \
    --signing-key-file pool_kes.skey
```

- create an operation certificate:
```
cardano-cli shelley node issue-op-cert \
    --kes-verification-key-file pool_kes.vkey \
    --cold-signing-key-file pool_cold.skey \
    --operational-certificate-issue-counter pool_cold.counter \
    --kes-period 30 \
    --out-file pool_operational.cert
```

- start the stake pool node using the previously created op cert:
```
cardano-node run \
    --topology mainnet-topology.json \
    --database-path db \
    --socket-path db/node.socket \
    --host-addr IP_ADDRESS \
    --port 3000\
    --config mainnet-config.json \
    --shelley-kes-key pool_kes.skey \
    --shelley-vrf-key pool_vrf.skey \
    --shelley-operational-certificate pool_operational.cert
```


scenarios:
1. create and start a stake pool with an op cert created with a valid `--kes-period` - the stake pool should create and sign blocks (this is the positive scenario)
2. create and start a stake pool with an op cert created with an expired `--kes-period` - the stake pool should not be able to sign the created blocks so the blocks should be dropped by the blockchain
3. try to create an op cert without `--kes-period` and start a node with it - it should not be possible
4. wait for the op cert / kes period to expire - the node should not be able to create and sign blocks anymore
5. change the values of "slotsPerKESPeriod" and "maxKESEvolutions" and execute all the above tests
6. use the same kes keys for 2 or more pools - I am not sure what should happen

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/192
https://github.com/input-output-hk/cardano-node-tests/pull/237
https://github.com/input-output-hk/cardano-node-tests/pull/241
https://github.com/input-output-hk/cardano-node-tests/pull/248
