### ISSUE TITLE
Support for running test automation on testnets

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node-tests#347]
Make it possible to run selected tests on testnets as well as on local cluster.

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/348

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/361
https://github.com/input-output-hk/cardano-node-tests/pull/363
https://github.com/input-output-hk/cardano-node-tests/pull/364

**Comment by dorin100** [comment]
It would be useful to be able to run the below tests using an already synced node:
- run "all" (available) tests 
- run specific tests
- have a test for load test (like creating 100s or 1000s or txs and sending them in parallel, waiting some time, and returning how many were processed (based on balances !?)

**Comment by dorin100** [comment]
Target environments:
- testnet
- staging
- shelley_qa

The node can run on Linux or Windows (the socket path is different but it can be provided as an argument or read from some file)

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/377

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/378

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/381

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/382

**Comment by mkoura** [comment]
Selected automated tests are now running on Shelley_qa and it'sa possible to start testing from synced blockchain. I'm going to close this issue and create another for enabling more tests on testnets.
