### ISSUE TITLE
[QA] - Retire (de-register) an existing stake pool

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#35]
- retire (de-register) an existing stake pool (you can create it first) 
- check that the stake pool was correctly retired

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/blob/167bae76cc17faea23c2e2aacba6f5cdba83750d/cardano_node_tests/tests/test_staking.py#L568
