### ISSUE TITLE
Tests - multi-assets scenarios - part 2

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#376]
1. It is impossible to create outputs that contain only custom tokens
2. each address must hold a minimum ada value (min-ada-value, currently set at 1 ada) so it should not be possible to create outputs that contain custom tokens + < 1 ada
3. tests for min_ada_value for multiple/different types of tokens
4. send/spend different custom tokens in different/the_same outputs of the same tx
5. mint and burn different tokens in the same tx
6. When minting/burning multi-assets, use different syntaxes:
```
INT policyid.assetname, e.g. 42 $MYPOLICY.myassetname
INT policyid, e.g. 42 $MYPOLICY (No asset name specified)
policyid.assetname, e.g $MYPOLICY.myassetname (This will mint only one of myassetname)
Multiple assets can be combined in the same multi-asset value using the + operator, e.g:
100 lovelace + 42 $MYPOLICY.foo + -2 $MYPOLICY.bar + 10 lovelace
```
7. test with max no of multi-assets per tx
8. check that the tx_fees for the transactions with multi_assets (mint, spend, burn) does not change from release to release.
(+ multiple different assets + actions (mint, spend, burn) in the same tx)
9. https://github.com/input-output-hk/cardano-node/issues/2337

- some useful info about min-ada-value - https://github.com/input-output-hk/cardano-ledger-specs/blob/master/doc/explanations/faq.rst

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/438
