### ISSUE TITLE
Multiple rewards streams

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#413]
here's a good scenario:
- alice and bob each have a stake pool, and each list carl as the reward account, but carl is not an owner of either
- carl delegates to alice

then carl should get rewards from 3 sources:
- member of alice's pool
- leader of alice's pool
- leader of bob's pool

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/807
