### ISSUE TITLE
[QA] - Create payment and stake keys and addresses

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#44]
- create 1 payment key pair
- create 1 payment address 
- create 1 stake key pair
- create 1 stake address

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/blob/167bae76cc17faea23c2e2aacba6f5cdba83750d/cardano_node_tests/tests/test_staking.py#L39
