### ISSUE TITLE
[QA] - Script Address Validation 

### ISSUE THREAD

**Issue by alan-mcnicholas** [input-output-hk/cardano-node-tests#45]
This ticket is to track the testing and automation (if possible) of script address validation changes.
Tooling will be provided by Duncan to do so; we should look to see if this is something that be can included as a common automated test.
The testing should comprise primarily of testing this scenario is handled on a local cluster and then ensuring that the same is true of one of our live networks (e.g. MC4, TestNet).

**Comment by mkoura** [comment]
No tooling for validation available yet.

**Comment by vix-io** [comment]
hi @alan-mcnicholas Tooling is now available and ready to test (merged this week 21/09, in current master)

**Comment by alan-mcnicholas** [comment]
Thanks @vix-io, @mkoura is it possible to add this to the current sprint? cc @ArturWieczorek  Many thanks :)

**Comment by mkoura** [comment]
Thanks @vix-io 
It's already planned for current sprint @alan-mcnicholas

**Comment by mkoura** [comment]
https://github.com/mkoura/cardano-node-tests/blob/c9605388b3829526adfc2689ea1953d27120d593/cardano_node_tests/tests/test_multisig.py#L126 (and rest of the multisig tests)
