### ISSUE TITLE
Add simple way of triggering the CLI tests on specific branch/commit_no

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#454]
The idea is to provide a simple way of triggering the CLI tests (all or specific ones) for developers (and not only) on specific cardano-node branches (or commit numbers).

It also should be easy to track the progress of the tests.

We also may split the tests into different islands (local cluster/shelley_qa, sanity, all, etc).

This has lower priority but I thought it would be good to track it here.

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/actions
