### ISSUE TITLE
db-sync tables data types validation

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#459]
for all the tables check the correct data types
return
- fields with missing/null values
- fields with different types/lengths than expected

**Comment by ArturWieczorek** [comment]
WIP: `cardano-db-sync` database schema validation and indexes check coming soon.

**Comment by ArturWieczorek** [comment]
### Schema and indexes check added

Each table is checked for expected field and it;s data type.
If value of inserted data is incorrect with DB schema then `cardanod-db-sync` will report error on its own.

Below screenshot from comparison of expected values for `13.0.5` with latest `cardano-db-sync` release `13.1.0.0`:

https://buildkite.com/input-output-hk/qa-db/builds/341#018539a0-953a-41db-9505-1273aed99b96

![image](https://user-images.githubusercontent.com/2938515/209129491-91d6485e-8dad-4a05-afa0-551e5f88c9ac.png)
