### ISSUE TITLE
[QA] - Transactions fees

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#46]
Submit transactions with different fee values:
- min fee
- fee < min fee
- fee = 0
- negative fee
- fee > min fee

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/blob/167bae76cc17faea23c2e2aacba6f5cdba83750d/cardano_node_tests/tests/test_transactions.py#L325-L424
