### ISSUE TITLE
Group the scripts per duration and provide option to run them separately

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#52]
It would be nice to have multiple options to run the scripts:
- the fastest ones (sanity)
- all of them
- custom tests (not sure this makes sense or if it is important)

**Comment by mkoura** [comment]
It is already possible with pytest. We can mark tests however we want (smoke, sanity, fast, ...) and run the group marked with the marker.

By default we run all test when launched using `make tests`.

We can also run specific test(s) on command line (like `pytest -k part_of_test_name`, `pytest -k TestClass`, `pytest path/to/test/file`, `pytest -k "not part_of_test_name" path/to/test/file`, etc.).
