### ISSUE TITLE
Check the code coverage for the CLI commands

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#53]
It would be nice to have a coverage of the CLI commands. This way we would know what CLI commands are not covered.

**Comment by mkoura** [comment]
We are collecting coverage info for each test run. During publishing of test report to our github page, we also publish coverage stats - https://input-output-hk.github.io/cardano-node-tests/cli_coverage.json Also badge icon is updated during test report publish - https://input-output-hk.github.io/cardano-node-tests/
