### ISSUE TITLE
Create reporting tool for the results

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#54]
It would be nice and useful to have a nice report with the results of the regression runs. 

To be included:
- date
- time
- node version
- tests + test results
- tbd

**Comment by mkoura** [comment]
We are now generating html report with all the info above for each test run.

We don't have CI to automatically run tests and publish reports, manually it can be done by publishing report on our github pages:
```
$ git fetch upstream test_reports # only needed first time
$ git checkout test_reports
$ git pull upstream test_reports
$ ./publi.sh .reports/report.html
```
The latest report is available on https://input-output-hk.github.io/cardano-node-tests/reports/last.html and the list of reports on https://input-output-hk.github.io/cardano-node-tests/
