### ISSUE TITLE
--tx-in-collateral cases

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#568]
- `--tx-in-collateral` is not needed for txes without Plutus scripts
- `--tx-in-collateral` < tx fee
- `--tx-in-collateral` > tx fee
- `--tx-in-collateral` = tx fee
- `--tx-in-collateral`  = `--tx-in` --> using the same public key both for collateral and input
- collateral cannot contain native tokens (utxo containing native tokens cannot be used as collateral)
-  

`--> It is part of the “2 phase validation” scheme introduced in Alonzo. It specifies inputs that are used as collateral in case any of the scripts in the transaction fail. The collateral inputs must cover the tx fees (times the collateralization factor which is a protocol param) and be ordinary pubkey inputs, not themselves scripts. The collateral inputs will not be consumed in the normal case that all scripts are valid. They will only be consumed if the scripts fail (in which case the normal tx ins will not be consumed). Collateral inputs are only needed for txs with Plutus scripts.`

**Comment by mkoura** [comment]
We are testing scenarios where collateral is below or above of what is required by tx fee and `collateralPercentage` settings.
