### ISSUE TITLE
add test for basic Plutus precompiled scripts 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#572]
`always-succeeds - demonstrates the two stages to use a "locking" Plutus script:
- Create tx output with a datum hash at the script address.
- Spend said tx output with the script

for the moment the transactions should be balanced manually but later there will be a CLI command for that. 

it would be nice to check that the fee for both the transactions remains the same over time

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/pull/573
