### ISSUE TITLE
Alonzo Protocol Parameters

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#592]
- "collateralPercentage": 100, --> how much of fee must be covered in collateral (100% or more)
- "maxCollateralInputs": 1,  --> used to limit the total number of collateral inputs
- "maxBlockExecutionUnits": 
- "maxTxSize": 16384,
- "costModels"
- "maxTxExecutionUnits"
- "executionUnitPrices"

PS: use/check (at least) the same values from mainnet

**maxCollateralInputs** 
- check that you can use multiple collaterals
- use more collaterals than permitted --> expect error; not possible to submit tx
- use no collaterals --> expect error; not possible to submit tx
- when the script is failing validation, ALL used collaterals are consumed

**collateralPercentage**
- check with always failing script that the correct collateralPercentage is required 
- provided collateral > tx fee (* collateralPercentage)
- provided collateral = tx fee (* collateralPercentage)
- provided collateral < tx fee --> expect error; not possible to submit tx

**Comment by mkoura** [comment]
Implemented.
