### ISSUE TITLE
Add coverage for `cardano-cli transaction build`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#631]
* `transaction build` does not need to be given the fee. Tt will be worked out automatically.
* `transaction build`does not need to be given script execution units. That will be worked out automatically.
* `transaction build`requires an extra flag for a change address (`--change-address`): and it will automatically put the right change into that address to make the transaction balance.
* `transaction build`needs access to a local node, whereas build-raw does not.

PS: we need to keep tests for `transaction build-raw` + 'transaction calculate-min-fee' too

**Comment by dorin100** [comment]
Negative cases for `transaction build`:
- there are not enough funds in the `--tx-in`

**Comment by mkoura** [comment]
Implemented.
