### ISSUE TITLE
MIR cert - part2

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#745]
Up to protocol version 5 (Alonzo), multiple MIR rewards going to the same address will overwrite (in the same epoch). In a single epoch, an address could have a payment from reserves **and** treasury (treasury and reserve payments are handled separately)?

Cases:
- up to PV5 (included) - send more MIR certs and validate that only the last one sent in the same epoch have effect
- starting with PV6 (included) - send more MIR certs and validate that all the certs sent (in the same epoch) have effect 

PS: latest is PV6 (Alonzo - October 2021 hard fork)
PS: multiple transfers are summed

related to https://github.com/input-output-hk/cardano-db-sync/issues/892

**Comment by mkoura** [comment]
Implemented in https://github.com/input-output-hk/cardano-node-tests/pull/841/ (for PV6, PV5 is no longer used).
