### ISSUE TITLE
test tx-execution-units

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#789]
cardano-cli governance create-update-proposal --max-tx-execution-units '(10000000000,11250000)' --out-file update.txt --epoch 305 --genesis-verification-key-file genesis.key

**Comment by mkoura** [comment]
We already test `--max-tx-execution-units` - https://github.com/input-output-hk/cardano-node-tests/blob/master/cardano_node_tests/tests/test_update_proposals.py#L132-L136
