### ISSUE TITLE
investigate "db-analyser tool"

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#794]
could this tool help us in any way? 
- https://github.com/input-output-hk/ouroboros-network/pull/3435/files

**Comment by ArturWieczorek** [comment]
< In progress >

Tried to use it with our local testnet cluster. I encountered some problems and decided to open a ticket:
https://github.com/input-output-hk/ouroboros-network/issues/3554

Slack Thread:
https://input-output-rnd.slack.com/archives/CDA6LUXAQ/p1640116503106600

**Comment by dorin100** [comment]
thank you @ArturWieczorek
