### ISSUE TITLE
add test for `cardano-cli address info` with `--out-file` specified

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/cardano-node-tests#906]
See https://github.com/input-output-hk/cardano-node-tests/blob/269a2c14685e1a62a82202bb35796928b74bf99b/cardano_node_tests/tests/test_cli.py#L194
See also implementation of `address_info` in clusterlib. 

Add a test that compares address info data when `--out-file` is/is not specified.

**Comment by saratomaz** [comment]
Implemented with [PR](https://github.com/input-output-hk/cardano-node-tests/pull/909)
