### ISSUE TITLE
automate "--tx-in-datum" options both for `transaction build` and `transaction build-raw`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#937]
- [x] --tx-in-datum-cbor-file
- [x] --tx-in-datum-json-file
- [x] more parameters added in the below PR

related to https://github.com/input-output-hk/cardano-node/pull/3483

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-clusterlib-py/pull/80
https://github.com/input-output-hk/cardano-node-tests/pull/938
