### ISSUE TITLE
transaction view --> "Add collateral inputs friendly output"

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#942]
related to https://github.com/input-output-hk/cardano-node/pull/3463

Whats new?
Now the cli command transaction view have a new parameters on the output named **collateral inputs**.

What is expected?
The new field should be null if no tx collateral's inputs are provided or present it in contrary case.

Scenarios:
- [x] no collateral in the tx (= existing tests --> it should not display any info in the new fields)
- [x] 1 valid collateral
- [x] multiple valid collaterals 
- [x] check tx view command for raw, signed and submitted txs
- [ ] collaterals from different payment addresses
- [ ] mix of valid and invalid collaterals 
- [ ] other scenarios ?
- [x] use all the cases both with `transaction build` and `transaction build-raw`

**Comment by saratomaz** [comment]
To test the "transaction view" command we need a valid transaction, so is not possible to test the command with invalid data. Even so, new tests are added to check invalid transactions submission, one with an invalid utxo as collateral and one with an insufficient collateral amount.
