### ISSUE TITLE
check metrics returned by kes-period-info command

### ISSUE THREAD

**Issue by saratomaz** [input-output-hk/cardano-node-tests#970]
**Node related PR**
#3683
#3697 now on #3718

**What is expected?**
The metrics returned by the command kes-period-info should be according to the operational certificate provided. All valid and invalid scenarios should check this.

_Hints to do it_
To check the validity of the metrics we should calculate the expected metrics and than compare the values returned by the command. The values returned by this command should be checked before and after the pool produced blocks

_Related thread_
https://input-output-rnd.slack.com/archives/GR599HMFX/p1646908332844489

**Comment by dorin100** [comment]
in the light of the latest observations, it would be ideal to check the values returned by this command both before and after the pool produced blocks
