### ISSUE TITLE
rewards withdrawal

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#98]
https://github.com/input-output-hk/cardano-node/blob/2c74060d02ec03c8b5a92a53447ca58c582d988c/doc/stake-pool-operations/withdraw-rewards.md#build-the-raw-transaction

**Comment by mkoura** [comment]
https://github.com/input-output-hk/cardano-node-tests/blob/c199d629daf66d4540f4feff04f5f52b330e0462/cardano_node_tests/tests/test_staking.py#L379
https://github.com/input-output-hk/cardano-node-tests/blob/c199d629daf66d4540f4feff04f5f52b330e0462/cardano_node_tests/tests/test_staking.py#L169
