### ISSUE TITLE
Vasil hard-fork (HFC)

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-node-tests#996]
- [x] check successful era migration - after era migration (from Alonzo to Vasil):
> - blocks are still created by stake pools
> - rewards are still paid
> - all the existing scripts are passing (in the Vasil era) (Shelley/Mary/Alonzo/Vasil transactions) - blocks, rewards, pool operation, etc
- [x] `query protocol parameters` CLI command return correct values (protocol version included)
- [x] `transaction view` output works for Vasil transactions and it contains all the new parameters when using Plutus v2
> - reference inputs, collateral return, collateral total, more data in the transaction outs (inline datums, reference scripts, other scenarios)
- [x] all the previous functionalities are working in the Vasil era
- [x] after the HF, the correct protocol version is advised in the block headers ([affected by this issue](https://github.com/input-output-hk/cardano-node/issues/4173))
- [x]  upgrade nightly pipelines with the Vasil era scripts
> - Script size - it should be smaller compared with Alonzo
> - Interpreter - it should be faster compared with Alonzo
> - Tx Cost - the cost for interacting with Plutus scripts should be smaller than in Alonzo (it should be cheaper to reference a script than to submit it)

- Mainnet approach --> https://github.com/input-output-hk/cardano-node-tests/issues/1158

- [x] cost model V2
   - [x] the next epoch after the HF, the cost model will need to be updated in order for Plutus V2 to take effect 
   - [x] the cost of the transactions without Plutus scripts should not be impacted by the second cost model --> https://github.com/input-output-hk/cardano-node-tests/issues/996#issuecomment-1144546694
   - [x] we can change any of the cost models with an update-proposal (make and confirm changes to different parameters of both cost-model_V1 and cost-model_V2, for parameters having the same name and also different names)
      - we’re using a positional translation, so the Plutus cost parameter names should be in the same relative positions, but they don’t need to be the same names

- [x] there is full backward compatibility between Plutus v1 and Plutus v2

**Comment by vfrsilva** [comment]
@dorin100 can you please add a point to test/review cost model for Plutus V1 and Plutus V2 after the Plutus V2 cost model is voted (1 epoch after HF)

**Comment by dorin100** [comment]
> @dorin100 can you please add a point to test/review cost model for Plutus V1 and Plutus V2 after the Plutus V2 cost model is voted (1 epoch after HF)

Done. Anyway, this new point generated some new open questions; check the main thread -->

**Comment by dorin100** [comment]
useful - https://github.com/cardano-foundation/CIPs/pull/318
